services:
  - type: web
    name: eml-logistics-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run prisma:generate && npx prisma db push --skip-generate && npm run prisma:seed
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: eml-african-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-vercel-frontend.vercel.app
